#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
EvaluatorAgent - Propagation chain quality evaluation agent

Evaluates quality of fault propagation chains generated by AnalysisAgent or InferenceAgent
from three dimensions:
1. Causal Logic Consistency - 40%
2. Chain Completeness - 35%
3. Layer Transition Rationality - 25%
"""

from .BaseAgent import BaseAgent
import os
import json


class EvaluatorAgent(BaseAgent):
    def __init__(self):
        """Initialize EvaluatorAgent"""
        super().__init__()

        # Load prompt templates
        prompt_dir = os.path.join(os.path.dirname(__file__), '..', 'prompts')

        with open(os.path.join(prompt_dir, 'chain_evaluation_system.txt'), 'r', encoding='utf-8') as f:
            self.system_prompt = f.read()

        with open(os.path.join(prompt_dir, 'chain_evaluation_user.txt'), 'r', encoding='utf-8') as f:
            self.user_prompt_template = f.read()

    def evaluate_chains(self, propagation_chains, causal_analysis, metric_analysis, iteration_context=None, save_path=None):
        """
        Evaluate propagation chain quality

        Args:
            propagation_chains (list): Propagation chain list, each chain contains chain_id, summary, confidence, chain
            causal_analysis (str): PCMCI causal analysis result (CSV format string)
            metric_analysis (list or str): Metric analysis result (JSON list or string)
            iteration_context (dict, optional): Iteration context (provided from round 2 onwards)
            save_path (str, optional): Evaluation result save path

        Returns:
            dict: Evaluation result containing overall_score, pass, chain_evaluations, recommendations, etc.
        """
        self.logger.info("Starting propagation chain quality evaluation")
        if iteration_context:
            self.logger.info(f"Iteration round: {iteration_context.get('current_iteration')}")

        try:
            # Save deep copy of original chains for adding to evaluation result
            import copy
            original_chains = copy.deepcopy(propagation_chains)

            # Prepare input data
            propagation_chains_str = json.dumps(propagation_chains, ensure_ascii=False, indent=2)

            # Process metric_analysis
            if isinstance(metric_analysis, str):
                # If it's a file path, read the file
                if os.path.exists(metric_analysis):
                    with open(metric_analysis, 'r', encoding='utf-8') as f:
                        metric_analysis_data = json.load(f)
                    metric_analysis_str = json.dumps(metric_analysis_data, ensure_ascii=False, indent=2)
                else:
                    # Assume it's a JSON string
                    metric_analysis_str = metric_analysis
            else:
                # Assume it's a list or dict
                metric_analysis_str = json.dumps(metric_analysis, ensure_ascii=False, indent=2)

            # Process causal_analysis
            if isinstance(causal_analysis, str) and os.path.exists(causal_analysis):
                # If it's a file path, read file content
                with open(causal_analysis, 'r', encoding='utf-8') as f:
                    causal_analysis_content = f.read()
            else:
                # Assume already string content
                causal_analysis_content = str(causal_analysis)

            # Process iteration_context
            iteration_context_str = ""
            if iteration_context:
                iteration_context_str = "\n\n## Iteration Context\n\n"
                iteration_context_str += "```json\n"
                iteration_context_str += json.dumps(iteration_context, ensure_ascii=False, indent=2)
                iteration_context_str += "\n```"

            # Fill user prompt
            user_prompt = self.user_prompt_template.format(
                propagation_chains=propagation_chains_str,
                causal_analysis=causal_analysis_content,
                metric_analysis=metric_analysis_str
            )

            # Append iteration_context to user_prompt if present
            if iteration_context_str:
                user_prompt += iteration_context_str

            # Call LLM for evaluation
            self.logger.info("Calling LLM for propagation chain evaluation")
            response = self.analyze_with_prompt(self.system_prompt, user_prompt)

            if response is None:
                raise Exception("LLM evaluation failed, response is empty")

            # Save raw response for debugging and analysis
            if save_path:
                raw_response_path = save_path.replace('.json', '_raw_response.txt')
                try:
                    os.makedirs(os.path.dirname(raw_response_path), exist_ok=True)
                    with open(raw_response_path, 'w', encoding='utf-8') as f:
                        f.write(response)
                    self.logger.info(f"Raw response saved to: {raw_response_path}")
                except Exception as e:
                    self.logger.warning(f"Failed to save raw response: {str(e)}")

            # Parse JSON response
            evaluation_result = self._parse_evaluation_response(response)

            # Add original chains to evaluation result
            evaluation_result['evaluated_chains'] = original_chains

            # Save evaluation result
            if save_path:
                self._save_evaluation_result(evaluation_result, save_path)
                self.logger.info(f"Evaluation result saved to: {save_path}")

            # Print evaluation summary
            self._print_evaluation_summary(evaluation_result)

            return evaluation_result

        except Exception as e:
            self.logger.error(f"Error evaluating propagation chains: {str(e)}")
            import traceback
            traceback.print_exc()
            raise

    def _parse_evaluation_response(self, response):
        """
        Parse evaluation result returned by LLM

        Args:
            response (str): Raw response from LLM

        Returns:
            dict: Parsed evaluation result
        """
        try:
            # Try to extract JSON portion
            original_response = response
            response = response.strip()

            # Method 1: If response contains markdown code block, extract JSON from it
            if '```' in response:
                # Find content between first ``` and last ```
                lines = response.split('\n')
                json_lines = []
                in_code_block = False

                for line in lines:
                    line_stripped = line.strip()
                    if line_stripped.startswith('```'):
                        if not in_code_block:
                            in_code_block = True
                            continue  # Skip ```json line
                        else:
                            break  # Closing ```
                    elif in_code_block:
                        json_lines.append(line)

                if json_lines:
                    response = '\n'.join(json_lines).strip()
                    self.logger.info("Extracted JSON from markdown code block")

            # Method 2: Try to find JSON object start and end positions
            if not response.startswith('{'):
                start_idx = response.find('{')
                if start_idx != -1:
                    response = response[start_idx:]
                    self.logger.info(f"Extracted JSON starting from position {start_idx}")

            if not response.endswith('}'):
                end_idx = response.rfind('}')
                if end_idx != -1:
                    response = response[:end_idx+1]
                    self.logger.info(f"Ended JSON extraction at position {end_idx}")

            # Parse JSON
            self.logger.info(f"Attempting to parse JSON, length: {len(response)} chars")
            evaluation_result = json.loads(response)

            # Validate required fields (new format)
            required_fields = ['summary', 'chain_evaluations']
            for field in required_fields:
                if field not in evaluation_result:
                    self.logger.warning(f"Evaluation result missing required field: {field}")

            # Validate summary sub-fields
            if 'summary' in evaluation_result:
                summary_fields = ['chain_count', 'hard_violation_count', 'soft_issue_count', 'overall_judgement']
                for field in summary_fields:
                    if field not in evaluation_result['summary']:
                        self.logger.warning(f"Evaluation result summary missing field: {field}")

            return evaluation_result

        except json.JSONDecodeError as e:
            self.logger.error(f"Failed to parse evaluation result JSON: {str(e)}")
            self.logger.error(f"Error position: line {e.lineno}, column {e.colno}, pos {e.pos}")

            # Output content near error
            try:
                lines = response.split('\n')
                if e.lineno <= len(lines):
                    error_line = lines[e.lineno - 1]
                    self.logger.error(f"Error line content: {error_line}")
                    if e.colno < len(error_line):
                        context_start = max(0, e.colno - 20)
                        context_end = min(len(error_line), e.colno + 20)
                        context = error_line[context_start:context_end]
                        self.logger.error(f"Error context: ...{context}...")
            except:
                pass

            # Output beginning and end of response
            self.logger.error(f"Response beginning (200 chars): {response[:200]}")
            self.logger.error(f"Response end (200 chars): {response[-200:]}")

            raise Exception(f"Evaluation result JSON parse failed: {str(e)}\nError position: line {e.lineno}, column {e.colno}")

    def _save_evaluation_result(self, evaluation_result, save_path):
        """
        Save evaluation result to JSON file

        Args:
            evaluation_result (dict): Evaluation result
            save_path (str): Save path
        """
        try:
            os.makedirs(os.path.dirname(save_path), exist_ok=True)

            with open(save_path, 'w', encoding='utf-8') as f:
                json.dump(evaluation_result, f, ensure_ascii=False, indent=2)

        except Exception as e:
            self.logger.error(f"Failed to save evaluation result: {str(e)}")
            raise

    def _print_evaluation_summary(self, evaluation_result):
        """
        Print evaluation summary information

        Args:
            evaluation_result (dict): Evaluation result
        """
        print(f"\n{'='*70}")
        print("Propagation Chain Quality Evaluation Results")
        print(f"{'='*70}")

        # Overall score
        overall_score = evaluation_result.get('overall_score', 0)
        pass_status = "✓ PASS" if evaluation_result.get('pass', False) else "✗ FAIL"

        print(f"\nOverall quality score: {overall_score:.4f} {pass_status}")

        # Evaluation summary
        if 'evaluation_summary' in evaluation_result:
            summary = evaluation_result['evaluation_summary']
            print(f"\nDimension scores:")
            print(f"  - Causal Logic Consistency: {summary.get('causal_logic_score', 0):.4f}")
            print(f"  - Chain Completeness:       {summary.get('completeness_score', 0):.4f}")
            print(f"  - Layer Transition Rationality: {summary.get('layer_rationality_score', 0):.4f}")

            print(f"\nIssue statistics:")
            print(f"  - Total issues: {summary.get('total_issues', 0)}")
            print(f"  - Critical issues: {summary.get('critical_issues', 0)}")
            print(f"  - High issues: {summary.get('high_issues', 0)}")
            print(f"  - Medium issues: {summary.get('medium_issues', 0)}")
            print(f"  - Low issues: {summary.get('low_issues', 0)}")

        # Per-chain scores
        if 'chain_evaluations' in evaluation_result:
            print(f"\nPer-chain scores:")
            for chain_eval in evaluation_result['chain_evaluations']:
                chain_id = chain_eval.get('chain_id', 'unknown')
                score = chain_eval.get('score', 0)
                issue_count = len(chain_eval.get('issues', []))

                print(f"\n  Chain {chain_id}:")
                print(f"    - Score: {score:.4f}")
                print(f"    - Issues: {issue_count}")

                # Print issues
                for issue in chain_eval.get('issues', []):
                    severity_icon = {
                        'critical': '🔴',
                        'high': '🟠',
                        'medium': '🟡',
                        'low': '🟢'
                    }.get(issue.get('severity', 'low'), '⚪')

                    print(f"    {severity_icon} [{issue.get('severity', 'unknown').upper()}] "
                          f"{issue.get('position', '')}: {issue.get('description', '')}")

        # Correction recommendations
        if 'recommendations' in evaluation_result and evaluation_result['recommendations']:
            print(f"\nCorrection recommendations:")
            for idx, rec in enumerate(evaluation_result['recommendations'], 1):
                print(f"  {idx}. {rec}")

        print(f"\n{'='*70}\n")


def create_evaluator():
    """Convenience function to create EvaluatorAgent instance"""
    return EvaluatorAgent()
